@Library('shared-library') _
pipeline {
    agent any

    stages {

        stage('Resources') {
            steps {
                 
                 
                HelloWExternal(surname:"Saittegin",name:"Beknazar")
            }
        }
    }
}
