@Library('shared-library') _
pipeline {
    agent {label 'slave2'}

    stages {

        stage('Resources') {
            steps {
                 
                 
                HelloWExternal(surname:"Saittegin",name:"Beknazar")
            }
        }
        stage('Sendemail') {
            steps {
                 
                 
                sendemail(surname:"Saittegin",name:"Beknazar")
            }
        }
    
}
